#!/usr/bin/env node
// Assemble the npm package into packages/ugas/build/ — the directory that gets published.
//
// The content is the same version tree publish-docs.yml ships to ugas.jbltx.com/v<version>/
// (placeholders resolved, SPEC.md -> sections/, genre index, schema bundle, rag/, and the
// checksummed index.json manifest), built by the same repo scripts, so a consumer that
// vendored files from the site finds them at the same relative paths here. It leaves out
// the rendered HTML and the AsciiDoc sources, which the site serves for reading.
//
// The version is the repo's own: the root package.json that changesets bumps (or
// UGAS_VERSION, with or without a leading v, to build another one).
//
// Needs: node, python3 with PyYAML, asciidoctor, pandoc.
//
// Usage: node scripts/build.mjs

import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const PKG = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = path.resolve(PKG, '..', '..');
const OUT = path.join(PKG, 'build');
const GEN = path.join(PKG, 'src', 'generated');

const rootVersion = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;
const VERSION = (process.env.UGAS_VERSION || rootVersion).replace(/^v/, '');
const TAG = `v${VERSION}`;
const PLACEHOLDER = '%%UGAS_VERSION%%';

const run = (cmd, args, opts = {}) => execFileSync(cmd, args, { stdio: ['ignore', 'inherit', 'inherit'], ...opts });

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = path.join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const pascal = (s) => s.split('_').map((w) => w[0].toUpperCase() + w.slice(1)).join('');

// 1. Resolve placeholders in a scratch copy of the sources, as publish-docs.yml does.
const work = mkdtempSync(path.join(tmpdir(), 'ugas-npm-'));
try {
  for (const entry of ['SPEC.adoc', 'docinfo.html', 'spec', 'schemas', 'genres', 'conformance']) {
    cpSync(path.join(ROOT, entry), path.join(work, entry), { recursive: true });
  }
  for (const dir of ['schemas', 'genres', 'conformance']) {
    for (const file of walk(path.join(work, dir))) {
      if (!/\.(json|ya?ml|md)$/.test(file)) continue;
      const text = readFileSync(file, 'utf8');
      if (text.includes(PLACEHOLDER)) writeFileSync(file, text.replaceAll(PLACEHOLDER, TAG));
    }
  }

  // 2. SPEC.adoc -> SPEC.md (asciidoctor + pandoc), the input of the section splitter.
  run('bash', [path.join(ROOT, 'scripts', 'generate-llm-files.sh'), work, work, TAG]);

  // 3. The version tree, then the consumer artifacts and the manifest over it.
  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });
  for (const entry of ['schemas', 'genres', 'conformance', 'SPEC.md']) {
    cpSync(path.join(work, entry), path.join(OUT, entry), { recursive: true });
  }
  run('bash', [path.join(ROOT, 'scripts', 'build-artifacts.sh'), OUT, TAG, path.join(work, 'llms.txt')]);
} finally {
  rmSync(work, { recursive: true, force: true });
}

// 4. Generated sources: version + schema ids, JSON imports, and entity types.
const manifest = JSON.parse(readFileSync(path.join(OUT, 'index.json'), 'utf8'));
if (manifest.version !== VERSION) throw new Error(`manifest version ${manifest.version} != ${VERSION}`);

const entityTypes = manifest.resources
  .filter((r) => r.kind === 'schema' && r.path.endsWith('.json'))
  .map((r) => path.basename(r.path, '.json'))
  .sort();
const schemaIds = {};
for (const type of entityTypes) {
  const id = JSON.parse(readFileSync(path.join(OUT, 'schemas', `${type}.json`), 'utf8')).$id;
  const expected = `https://ugas.jbltx.com/${TAG}/schemas/${type}.json`;
  if (id !== expected) throw new Error(`schemas/${type}.json $id is ${id}, expected ${expected}`);
  schemaIds[type] = id;
}

rmSync(GEN, { recursive: true, force: true });
mkdirSync(path.join(GEN, 'types'), { recursive: true });
const banner = '// Generated by scripts/build.mjs. Do not edit.\n';

writeFileSync(
  path.join(GEN, 'meta.ts'),
  `${banner}
/** The UGAS release this package ships; the npm version is the same string. */
export const VERSION = ${JSON.stringify(VERSION)};

/** Every entity type with a schema, as named in \`$schema\` ids (\`schemas/<type>.json\`). */
export const ENTITY_TYPES = ${JSON.stringify(entityTypes)} as const;

export type EntityType = (typeof ENTITY_TYPES)[number];

/** The \`$schema\` id an entity of each type carries at this version. */
export const SCHEMA_IDS: { readonly [T in EntityType]: string } = Object.freeze(${JSON.stringify(schemaIds, null, 2)});

/** The \`$schema\` id for an entity type at this version. */
export function schemaId(type: EntityType): string {
  return SCHEMA_IDS[type];
}
`,
);

const jsonImport = (name, rel) => `import ${name} from '${rel}' with { type: 'json' };`;
writeFileSync(
  path.join(GEN, 'data.js'),
  `${banner}${[
    jsonImport('manifest', '../../index.json'),
    jsonImport('bundle', '../../schemas/bundle.json'),
    ...entityTypes.map((t) => jsonImport(`schema_${t}`, `../../schemas/${t}.json`)),
  ].join('\n')}

export const schemas = Object.freeze({
${entityTypes.map((t) => `  ${t}: schema_${t},`).join('\n')}
});

export { manifest, bundle };
`,
);
writeFileSync(
  path.join(GEN, 'data.d.ts'),
  `${banner}import type { EntityType } from './meta.js';

/** A Draft-07 JSON Schema document. */
export type JsonSchema = { readonly [key: string]: unknown };

/** Per-type JSON Schemas (\`schemas/<type>.json\`). */
export declare const schemas: { readonly [T in EntityType]: JsonSchema };

/** Every schema in one offline-resolvable document (\`schemas/bundle.json\`). */
export declare const bundle: JsonSchema;

/** The release manifest (\`index.json\`): every packaged file with its kind and sha256. */
export declare const manifest: {
  readonly spec: 'ugas';
  readonly version: string;
  readonly resources: readonly {
    readonly id: string;
    readonly kind: string;
    readonly title: string;
    readonly path: string;
    readonly url: string;
    readonly mediaType: string;
    readonly bytes: number;
    readonly sha256: string;
  }[];
};
`,
);

const typeNames = {};
for (const type of entityTypes) {
  const schema = JSON.parse(readFileSync(path.join(OUT, 'schemas', `${type}.json`), 'utf8'));
  const name = pascal(type);
  typeNames[type] = name;
  const ts = await compile({ ...schema, title: name }, name, {
    bannerComment: `${banner}// From schemas/${type}.json (${schemaIds[type]}).`,
    cwd: path.join(OUT, 'schemas'),
    declareExternallyReferenced: true,
    format: true,
  });
  writeFileSync(path.join(GEN, 'types', `${type}.ts`), ts);
}
writeFileSync(
  path.join(GEN, 'types', 'index.ts'),
  `${banner}${entityTypes.map((t) => `import type { ${typeNames[t]} } from './${t}.js';`).join('\n')}

export type { ${entityTypes.map((t) => typeNames[t]).join(', ')} };

/** The entity type for each \`$schema\` type name. */
export interface EntityByType {
${entityTypes.map((t) => `  ${t}: ${typeNames[t]};`).join('\n')}
}

/** Any UGAS entity. */
export type UgasEntity = EntityByType[keyof EntityByType];
`,
);

// 5. Compile, then ship the hand-written JS/d.ts pair tsc does not emit.
run(path.join(PKG, 'node_modules', '.bin', 'tsc'), ['-p', path.join(PKG, 'tsconfig.json')]);
for (const f of ['data.js', 'data.d.ts']) cpSync(path.join(GEN, f), path.join(OUT, 'dist', 'generated', f));

// 6. The published package.json: this one, with the release version and no dev-only fields.
const pkg = JSON.parse(readFileSync(path.join(PKG, 'package.json'), 'utf8'));
delete pkg.scripts;
delete pkg.devDependencies;
pkg.version = VERSION;
writeFileSync(path.join(OUT, 'package.json'), `${JSON.stringify(pkg, null, 2)}\n`);
cpSync(path.join(PKG, 'README.md'), path.join(OUT, 'README.md'));
cpSync(path.join(ROOT, 'LICENSE'), path.join(OUT, 'LICENSE'));

for (const required of ['dist/index.js', 'dist/index.d.ts', 'schemas/bundle.json', 'sections/index.json', 'index.json']) {
  if (!existsSync(path.join(OUT, required))) throw new Error(`build is missing ${required}`);
}
console.log(`Built ugas ${VERSION} into ${path.relative(ROOT, OUT)}/ (${manifest.resources.length} manifest resources)`);
